config/routes.rb
Rails.application.routes.draw do
  root 'hotels#landing'

  devise_for :users, path: '', skip: %i[registrations], path_names: {
    sign_in: 'login',
    sign_out: 'logout'
  }
  as :user do
    get "/sign_up" => "devise/registrations#new", :as => :new_user_registration
    post "/" => "devise/registrations#create", :as => :user_registration
  end

  resources :hotels do
    resources :comments, only: %i[create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  has_one :hotel

  validates :country, :state, :city, :street, presence: true

  def save_if_given(address)
    result = { given: false, saved: false }

    if address.present? && given?(address)
      self.country = address[:country]
      self.state = address[:state]
      self.city = address[:city]
      self.street = address[:street]

      result[:given] = true
      result[:saved] = save
    end

    result
  end

  private

  def given?(address)
    given = false

    if address[:country].present? || address[:state].present? ||
       address[:city].present? || address[:street].present?
      given = true
    end

    given
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :hotel

  validates :message, presence: true
  validates_numericality_of :rating, only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5,
                            message: "can only be whole number between 1 and 5."

  def self.average_hotel_rating(hotel_id)
    Comment.where(hotel_id: hotel_id).average(:rating)
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  belongs_to :user
  belongs_to :address, optional: true
  has_many :comments

  mount_uploader :photo, HotelPhotoUploader

  validates :title, :star_rating, presence: true
  validates :price_for_room, numericality: true, allow_nil: true
  validates_numericality_of :star_rating, only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5,
                            message: "can only be whole number between 1 and 5."

  def self.top_five_hotels
    Hotel.order(star_rating: :desc).limit(5)
  end

  def update_rating
    rating = Comment.average_hotel_rating(id)

    return if rating.nil?

    update_attribute(:star_rating, rating.round)
  end

  def blank_stars
    5 - star_rating
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :hotels
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = current_user.comments.build(comment_params)
    hotel_id = params[:hotel_id]

    unless @comment.save
      return redirect_to hotel_path(hotel_id),
                         flash: { alert: @comment.errors.full_messages }
    end

    update_hotel_if_present(hotel_id)

    redirect_to hotel_path(hotel_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:rating, :message, :hotel_id)
  end

  def update_hotel_if_present(hotel_id)
    hotel = Hotel.find(hotel_id)
    hotel.update_rating if hotel.present?
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create update edit destroy]

  def landing
    @hotels = Hotel.top_five_hotels
    render action: :landing, layout: "landing"
  end

  def index
    @hotels = Hotel.order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
    @hotel = Hotel.new
    @address = Address.new
  end

  def show
    @hotel = Hotel.find(params[:id])
    @comments = Comment.where(hotel_id: params[:id]).includes(:user).page(params[:page]).per(5)
    @comment = Comment.new
  end

  def update; end

  def edit; end

  def destroy; end

  def create
    @hotel = current_user.hotels.build(hotel_params)
    @address = Address.new

    address_status = @address.save_if_given(params[:hotel][:address])
    if address_status[:given]
      return render :new unless address_status[:saved]
      @hotel.address = @address
    end

    if @hotel.save
      redirect_to @hotel
    else
      render :new
    end
  end

  private

  def hotel_params
    params.require(:hotel).permit(:title, :star_rating, :breakfast_included, :room_description, :price_for_room, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/hotel_helper.rb
module HotelHelper
end

app/views/hotels/_breakfast_included.html.haml
- if included
  = image_tag "icons/icon-with-food.png", title: "Breakfast included"
- else
  = image_tag "icons/icon-no-food.png", title: "Breakfast not included"

app/views/hotels/_star_rating.html.haml
- stars.times do |star|
    .star
- blank_stars.times do |blank_star|
    .star-blank

app/views/hotels/index.html.haml
.offset
%h1.text-center Hotels list
- @hotels.each do |hotel|
  .hotel-item
    .hotel-img
      = image_tag(hotel.photo.list.url || "no-image-hotels.png")

    .hotel-list
      %p= hotel.title
      = render "star_rating", stars: hotel.star_rating, blank_stars: hotel.blank_stars
      .price
        = "Price for room: #{hotel.price_for_room || "---"}$"
      = render "breakfast_included", included: hotel.breakfast_included
    = link_to "View details", hotel, class: "view-button"
.paginator-wrapper
  = paginate @hotels

app/views/hotels/landing.html.haml
.row.align-items-center.justify-content-center
  .form--desc.rounded.pb_form_v1_landing
    .row
      - @hotels.each do |hotel|
        .col-2_5
          = image_tag (hotel.photo.landing.url || "no-image-landing.png"), width: 200, height: 200, class: "img-border"
          .stars
            = render "star_rating", stars: hotel.star_rating, blank_stars: hotel.blank_stars
          .hotels-label= hotel.title

app/views/hotels/new.html.haml
.offset
.col-md-12
  = form_for @hotel, html: { class: "bg-white pb_form_v1" } do |f|
    .registration-form.text-center
      %text.pb_text-gray-900 Adding Hotel
    %br/
    %ul#error_explanation
      - f.object.errors.full_messages.each do |message|
        %li= message
    .form-group
      1. What was the name of the hotel*
      = f.text_field :title, class: "form-control pb_height-50 reverse", placeholder: "Title"
    .form-group
      2. Breakfast included?
      %br/
      ._middle
        = f.check_box :breakfast_included, class: "checkbox-zoomer"
        = f.label :breakfast_included, "Yes,it's included"
    .form-group
      3. Do you like this?*
      %br/
      #reviewStars-input
        = f.radio_button :star_rating, 5, id: "star-4"
        %label{:for => "star-4", :title => "gorgeous"}
        = f.radio_button :star_rating, 4, id: "star-3"
        %label{:for => "star-3", :title => "good"}
        = f.radio_button :star_rating, 3, id: "star-2"
        %label{:for => "star-2", :title => "regular"}
        = f.radio_button :star_rating, 2, id: "star-1"
        %label{:for => "star-1", :title => "poor"}
        = f.radio_button :star_rating, 1, id: "star-0"
        %label{:for => "star-0", :title => "bad"}
      %br/
      %br/
      %br/
      .form-group
        .row
          .col-2
            .form-group
              4. Country
            .form-group
              5. State
            .form-group
              6. City
            .form-group
              7. Street
          .col-4
            = f.fields_for @address do |a|
              .form-group-address
                = a.text_field :country, placeholder: "Country", class: "form-control reverse"
              .form-group-address
                = a.text_field :state, placeholder: "State", class: "form-control reverse"
              .form-group-address
                = a.text_field :city, placeholder: "City", class: "form-control reverse"
              .form-group-address
                = a.text_field :street, placeholder: "Street", class: "form-control reverse"
      8. Room description
      = f.text_area :room_description, placeholder: "Room was...", class: "form-control reverse", rows: 6
    .form-group
      9. Choose photo
      = f.file_field :photo, accept: "image/png,image/jpeg,image/gif"
      %text.small
    .form-group
      10. Price for room
      = f.number_field :price_for_room, min: 0, placeholder: "0", class: "form-control-price reverse"
      $
    .form-group.div-center
      = f.submit "Add", class: "btn btn-danger btn-center btn-lg pb_btn-pill btn-shadow-blue"

app/views/hotels/show.html.haml
.offset
.hotel-item-1
  %br/
  %p.card_title{:align => "center"}= @hotel.title
  .container
    .row
      .col-md-8
        .hotel-img-details
          = image_tag (@hotel.photo.details.url || "no-image-details.png")
      .col-md-4
        .bck_white
          = render "star_rating", stars: @hotel.star_rating, blank_stars: @hotel.blank_stars
          %p.price= (@hotel.price_for_room.to_s || "---") + "$/night"
          - if @hotel.address.present?
            %p.card_info_text Address:
            %p.card_info_text= "#{@hotel.address.country}, #{@hotel.address.state}"
            %p.card_info_text= "#{@hotel.address.city}, #{@hotel.address.street}"
          = render "breakfast_included", included: @hotel.breakfast_included
          %p
  .info_block
    %text= @hotel.room_description
    %div
    - if @comments.present?
      %div{ style: "margin-top: 20px"}
        %strong
          Comments:
      - @comments.each do |comment|
        .comment
          %div
            = "User: #{comment.user.email.partition("@").first}"
            = "Rating: #{comment.rating}"
            .pull-right
              = "Created at: #{comment.created_at.strftime("%F %T")}"
          %div
            = comment.message
      = paginate @comments

    = alert
    %div{style: "margin-top: 20px"}
    - if user_signed_in?
      = form_for [@hotel, @comment] do |f|
        Rate this hotel
        .form-group
          #reviewStars-input
            = f.radio_button :rating, 5, id: "star-4"
            %label{:for => "star-4", :title => "gorgeous"}
            = f.radio_button :rating, 4, id: "star-3"
            %label{:for => "star-3", :title => "good"}
            = f.radio_button :rating, 3, id: "star-2"
            %label{:for => "star-2", :title => "regular"}
            = f.radio_button :rating, 2, id: "star-1"
            %label{:for => "star-1", :title => "poor"}
            = f.radio_button :rating, 1, id: "star-0"
            %label{:for => "star-0", :title => "bad"}
          = f.text_area :message, placeholder: "Comment...", rows: 3, class: "form-control reverse"
          = f.hidden_field :hotel_id, value: @hotel.id

          = f.submit class: "btn btn-danger btn-center btn-lg btn-shadow-blue", value: "Add comment", style: "margin-top: 10px"
    - else
      .text-center Only registered users can rate hotels

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title HotStar
    = csrf_meta_tags
    = csp_meta_tag
    %link{:href => "https://fonts.googleapis.com/css?family=Crimson+Text:400,400i,600|Montserrat:200,300,400", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css", :rel => "stylesheet"}/
    = stylesheet_link_tag    'bootstrap/bootstrap', media: 'all'
    = stylesheet_link_tag    'style', media: 'all'
    = stylesheet_link_tag    'landing-2', media: 'all'
    = stylesheet_link_tag    'hotel_card', media: 'all'
    = stylesheet_link_tag    'zhoraStyle', media: 'all'
    = stylesheet_link_tag    'hotels_page', media: 'all'
    = yield :additional_css
  %body{"data-offset" => "200", "data-spy" => "scroll", "data-target" => "#pb-navbar"}
    = render "layouts/components/navigation"
    %section#section-home.pb_cover_v3.cover-bd-red.cover-bg-opacity.text-left.pb_gradient_v1.pb_form_v1
      .container
        = yield

    = render "layouts/components/footer"
    = render "layouts/components/loader"

    = javascript_include_tag 'jquery.min'
    = javascript_include_tag 'popper.min'
    = javascript_include_tag 'bootstrap.min'
    = javascript_include_tag 'application'
    = javascript_include_tag 'jquery.easing.1.3'
    = javascript_include_tag 'main'
    = yield :additional_js

app/views/layouts/components/_footer.html.haml
%footer.pb_footer.bg-light{:role => "contentinfo"}
  .container
    .row.text-center
      .col
        %ul.list-inline
          %li.list-inline-item
            %a.p-2{:href => "#"}
              %i.fa.fa-vk
          %li.list-inline-item
            %a.p-2{:href => "#"}
              %i.fa.fa-facebook
          %li.list-inline-item
            %a.p-2{:href => "#"}
              %i.fa.fa-telegram
    .row
      .col.text-center
        %p.pb_font-14
          © 2018
          = link_to 'HotStart', root_path
          All Rights Reserved.
          %br/
          Designed &amp; Developed by
          = link_to 'S.V.E.N team', 'https://gitlab.com/Infesiron/sven'

app/views/layouts/components/_loader.html.haml
#pb_loader.show.fullscreen
  %svg.circular{:height => "48px", :width => "48px"}
    %circle.path-bg{:cx => "24", :cy => "24", :fill => "none", :r => "22", :stroke => "#eeeeee", "stroke-width" => "4"}
    %circle.path{:cx => "24", :cy => "24", :fill => "none", :r => "22", :stroke => "#1d82ff", "stroke-miterlimit" => "10", "stroke-width" => "4"}

app/views/layouts/components/_navigation.html.haml
%nav#pb-navbar.navbar.navbar-expand-lg.navbar-dark.pb_navbar.pb_scrolled-light
  .container
    %h6.navbar-brand{:href => "index.html"}
      %text#logoHotel.logo HotStar
    = image_tag "logo.png", width: 125, height: 125, id: "logoHotel-img"
    %button.navbar-toggler.ml-auto{"aria-controls" => "probootstrap-navbar", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#probootstrap-navbar", "data-toggle" => "collapse", :type => "button"}
      %span
        %i.ion-navicon
    #probootstrap-navbar.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        %li.nav-item
          = link_to "Home", root_path, class: "nav-link"
        %li.nav-item
          = link_to "Hotels", hotels_path, class: "nav-link"
        - if user_signed_in?
          %li.nav-item
            = link_to "Add Hotel", new_hotel_path, class: "nav-link"
          %li.nav-item.cta-btn.ml-xl-2.ml-lg-2.ml-md-0.ml-sm-0.ml-0
            = link_to destroy_user_session_path, class: "nav-link", method: :delete do
              %span.pb_rounded-4.px-4 Logout
        - else
          %li.nav-item.cta-btn.ml-xl-2.ml-lg-2.ml-md-0.ml-sm-0.ml-0
            = link_to new_user_session_path, class: "nav-link" do
              %span.pb_rounded-4.px-4 Sign in/up

app/views/layouts/landing.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title HotStar
    = csrf_meta_tags
    = csp_meta_tag
    %link{:href => "https://fonts.googleapis.com/css?family=Crimson+Text:400,400i,600|Montserrat:200,300,400", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css", :rel => "stylesheet"}/
    = stylesheet_link_tag    'bootstrap/bootstrap', media: 'all'
    = stylesheet_link_tag    'style', media: 'all'
    = stylesheet_link_tag    'landing-2', media: 'all'
    = stylesheet_link_tag    'hotel_card', media: 'all'
    = stylesheet_link_tag    'hotels_page', media: 'all'
    = stylesheet_link_tag    'zhoraStyle', media: 'all'
    = yield :additional_css
  %body{ style: "background-image:url('#{image_path("landing.jpg")}');width:100%;height:100%;border:1px solid black; background-repeat: no-repeat; background-size: cover;"}
    = render "layouts/components/navigation"
    .landing-words
      %h2{:style => "color:white"} Register, make your choice!
      .sub-heading
        %p.mb-4{:style => "color:white"}
          You can add visited hotels all over the world,
          %br
          and express your opinion about them
        %p.mb-5
          = link_to hotels_path, class: "btn btn-danger btn-lg pb_btn-pill smoothscroll" do
            %span.pb_font-14.text-uppercase.pb_letter-spacing-1 view added
    %h4.mb-4.landing-best-part{:style => "color: ghostwhite"} Best hotels in the world in your opinion
    %section#section-home.landing-main-part
    .landing-main-part
      .container
        = yield



    = render "layouts/components/footer"
    = render "layouts/components/loader"

    = javascript_include_tag 'jquery.min'
    = javascript_include_tag 'popper.min'
    = javascript_include_tag 'bootstrap.min'
    = javascript_include_tag 'application'
    = javascript_include_tag 'jquery.easing.1.3'
    = javascript_include_tag 'main'
    = yield :additional_js

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>